-- Contract Repository — full database setup
-- Run this in Supabase: SQL Editor → + New query → paste → Run
-- Do NOT open a saved snippet; create a fresh query.

-- =============================================================================
-- 1. Tables
-- =============================================================================

create table if not exists contracts (
  id uuid primary key default gen_random_uuid(),
  contract_number integer generated by default as identity unique,
  title text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz default now()
);

create table if not exists documents (
  id uuid primary key default gen_random_uuid(),
  contract_id uuid references contracts(id) on delete cascade,
  role text not null check (role in ('original', 'annex', 'amendment', 'renewal', 'correspondence', 'other')),
  storage_path text not null,
  original_filename text not null,
  generated_filename text,
  extracted_text text,
  processing_status text not null default 'pending' check (processing_status in ('pending', 'processing', 'complete', 'failed')),
  uploaded_via text default 'ui',
  created_at timestamptz default now()
);

create table if not exists metadata_fields (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  label text not null,
  category text not null,
  field_type text not null check (field_type in ('text', 'date', 'number', 'boolean', 'enum')),
  enum_options text[],
  playbook_prompt text not null,
  is_builtin boolean default false,
  created_at timestamptz default now()
);

create table if not exists metadata_values (
  id uuid primary key default gen_random_uuid(),
  contract_id uuid references contracts(id) on delete cascade,
  field_id uuid references metadata_fields(id) on delete cascade,
  value text,
  confidence numeric,
  confirmed boolean default false,
  source_document_id uuid references documents(id),
  evidence_page integer,
  evidence_text text,
  updated_at timestamptz default now(),
  unique (contract_id, field_id)
);

create table if not exists contract_relationships (
  id uuid primary key default gen_random_uuid(),
  contract_a_id uuid references contracts(id) on delete cascade,
  contract_b_id uuid references contracts(id) on delete cascade,
  relationship_type text not null,
  confirmed boolean default false,
  created_at timestamptz default now()
);

create table if not exists naming_settings (
  id uuid primary key default gen_random_uuid(),
  template text not null default '{contract_type}_{counterparty}_{effective_date}_{document_role}',
  keep_original_name boolean default true
);

create table if not exists legal_entities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  registration_number text,
  country text,
  vat_number text,
  notes text,
  created_at timestamptz default now(),
  unique (name)
);

create table if not exists counterparties (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  registration_number text,
  country text,
  notes text,
  created_at timestamptz default now(),
  unique (name)
);

create table if not exists contract_types (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  notes text,
  created_at timestamptz default now(),
  unique (name)
);

alter table contracts
  add column if not exists legal_entity_id uuid references legal_entities(id) on delete set null;

alter table contracts
  add column if not exists counterparty_id uuid references counterparties(id) on delete set null;

alter table contracts
  add column if not exists contract_type_id uuid references contract_types(id) on delete set null;

-- =============================================================================
-- 2. Storage bucket
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('contracts', 'contracts', false)
on conflict (id) do nothing;

-- =============================================================================
-- 3. Row Level Security
-- =============================================================================

alter table contracts enable row level security;
alter table documents enable row level security;
alter table metadata_fields enable row level security;
alter table metadata_values enable row level security;
alter table contract_relationships enable row level security;
alter table naming_settings enable row level security;
alter table legal_entities enable row level security;
alter table counterparties enable row level security;
alter table contract_types enable row level security;

create table if not exists metadata_review_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  user_email text,
  contract_id uuid references contracts(id) on delete cascade,
  field_id uuid references metadata_fields(id) on delete set null,
  action text not null check (action in ('confirm', 'correct')),
  points integer not null check (points in (1, 5)),
  created_at timestamptz default now()
);

create index if not exists metadata_review_events_user_id_idx
  on metadata_review_events(user_id);

alter table metadata_review_events enable row level security;

-- Drop existing policies if re-running (safe on fresh project)
drop policy if exists "Authenticated users can read contracts" on contracts;
drop policy if exists "Authenticated users can insert contracts" on contracts;
drop policy if exists "Authenticated users can update contracts" on contracts;
drop policy if exists "Authenticated users can read documents" on documents;
drop policy if exists "Authenticated users can insert documents" on documents;
drop policy if exists "Authenticated users can update documents" on documents;
drop policy if exists "Authenticated users can read metadata_fields" on metadata_fields;
drop policy if exists "Authenticated users can insert metadata_fields" on metadata_fields;
drop policy if exists "Authenticated users can read metadata_values" on metadata_values;
drop policy if exists "Authenticated users can insert metadata_values" on metadata_values;
drop policy if exists "Authenticated users can update metadata_values" on metadata_values;
drop policy if exists "Authenticated users can read relationships" on contract_relationships;
drop policy if exists "Authenticated users can insert relationships" on contract_relationships;
drop policy if exists "Authenticated users can read naming_settings" on naming_settings;
drop policy if exists "Authenticated users can update naming_settings" on naming_settings;
drop policy if exists "Authenticated users can read contract files" on storage.objects;
drop policy if exists "Service role manages contract files" on storage.objects;
drop policy if exists "Authenticated users can read legal_entities" on legal_entities;
drop policy if exists "Authenticated users can insert legal_entities" on legal_entities;
drop policy if exists "Authenticated users can update legal_entities" on legal_entities;
drop policy if exists "Authenticated users can delete legal_entities" on legal_entities;
drop policy if exists "Authenticated users can read counterparties" on counterparties;
drop policy if exists "Authenticated users can insert counterparties" on counterparties;
drop policy if exists "Authenticated users can update counterparties" on counterparties;
drop policy if exists "Authenticated users can delete counterparties" on counterparties;
drop policy if exists "Authenticated users can read contract_types" on contract_types;
drop policy if exists "Authenticated users can insert contract_types" on contract_types;
drop policy if exists "Authenticated users can update contract_types" on contract_types;
drop policy if exists "Authenticated users can delete contract_types" on contract_types;
drop policy if exists "Authenticated users can read metadata_review_events" on metadata_review_events;
drop policy if exists "Authenticated users can insert metadata_review_events" on metadata_review_events;

create policy "Authenticated users can read contracts" on contracts for select to authenticated using (true);
create policy "Authenticated users can insert contracts" on contracts for insert to authenticated with check (true);
create policy "Authenticated users can update contracts" on contracts for update to authenticated using (true);
create policy "Authenticated users can delete contracts" on contracts for delete to authenticated using (true);

create policy "Authenticated users can read documents" on documents for select to authenticated using (true);
create policy "Authenticated users can insert documents" on documents for insert to authenticated with check (true);
create policy "Authenticated users can update documents" on documents for update to authenticated using (true);

create policy "Authenticated users can read metadata_fields" on metadata_fields for select to authenticated using (true);
create policy "Authenticated users can insert metadata_fields" on metadata_fields for insert to authenticated with check (true);

create policy "Authenticated users can read metadata_values" on metadata_values for select to authenticated using (true);
create policy "Authenticated users can insert metadata_values" on metadata_values for insert to authenticated with check (true);
create policy "Authenticated users can update metadata_values" on metadata_values for update to authenticated using (true);

create policy "Authenticated users can read relationships" on contract_relationships for select to authenticated using (true);
create policy "Authenticated users can insert relationships" on contract_relationships for insert to authenticated with check (true);

create policy "Authenticated users can read naming_settings" on naming_settings for select to authenticated using (true);
create policy "Authenticated users can update naming_settings" on naming_settings for update to authenticated using (true);

create policy "Authenticated users can read legal_entities" on legal_entities for select to authenticated using (true);
create policy "Authenticated users can insert legal_entities" on legal_entities for insert to authenticated with check (true);
create policy "Authenticated users can update legal_entities" on legal_entities for update to authenticated using (true);
create policy "Authenticated users can delete legal_entities" on legal_entities for delete to authenticated using (true);

create policy "Authenticated users can read counterparties" on counterparties for select to authenticated using (true);
create policy "Authenticated users can insert counterparties" on counterparties for insert to authenticated with check (true);
create policy "Authenticated users can update counterparties" on counterparties for update to authenticated using (true);
create policy "Authenticated users can delete counterparties" on counterparties for delete to authenticated using (true);

create policy "Authenticated users can read contract_types" on contract_types for select to authenticated using (true);
create policy "Authenticated users can insert contract_types" on contract_types for insert to authenticated with check (true);
create policy "Authenticated users can update contract_types" on contract_types for update to authenticated using (true);
create policy "Authenticated users can delete contract_types" on contract_types for delete to authenticated using (true);

create policy "Authenticated users can read metadata_review_events" on metadata_review_events for select to authenticated using (true);
create policy "Authenticated users can insert metadata_review_events" on metadata_review_events for insert to authenticated with check (true);

create policy "Authenticated users can read contract files"
on storage.objects for select to authenticated
using (bucket_id = 'contracts');

create policy "Service role manages contract files"
on storage.objects for all to service_role
using (bucket_id = 'contracts');

-- =============================================================================
-- 4. Seed data
-- =============================================================================

insert into metadata_fields (key, label, category, field_type, playbook_prompt, is_builtin) values
  ('contract_type', 'Contract Type', 'core', 'text', 'Identify the contract type. Return ONLY an exact name from the known contract types list provided during extraction. If none match, return null.', true),
  ('legal_entity', 'Legal entity', 'core', 'text', 'Identify which of OUR legal entities is a party to this contract. Use only a name from the known legal entities list provided during extraction. Return null if none of our entities appear in the contract.', true),
  ('counterparty', 'Counterparty', 'core', 'text', 'Extract the EXTERNAL party to this contract (not our own legal entities). Return only the counterparty name. If multiple external parties appear, return the primary one. Never include names from our known legal entities list.', true),
  ('effective_date', 'Effective Date', 'core', 'date', 'Find the effective date or commencement date of the contract. Return in ISO format YYYY-MM-DD.', true),
  ('expiry_date', 'Expiry Date', 'core', 'date', 'Find the expiration, termination, or end date of the contract. Return in ISO format YYYY-MM-DD. Return null if no fixed end date.', true),
  ('value', 'Contract Value', 'core', 'text', 'Extract the total contract value or annual value including currency (e.g. EUR 50,000). Return null if not specified.', true),
  ('notice_period', 'Notice period', 'core', 'text', 'Extract the notice period required for termination or non-renewal. Return ONLY valid JSON with amount, unit (days, business_days, weeks, months, years, or other), and purpose (any_time, avoid_auto_renewal, avoid_auto_termination, or other). Follow the contract unit wording.', true),
  ('automatic_renewal', 'Automatic renewal', 'core', 'boolean', 'Determine whether the contract automatically renews or extends at the end of its term unless notice is given. Return true, false, or null if unclear.', true)
on conflict (key) do nothing;

insert into naming_settings (template, keep_original_name)
select '{contract_type}_{counterparty}_{effective_date}_{document_role}', true
where not exists (select 1 from naming_settings limit 1);
