-- Contracts are "cases" — a container, not a single file
create table contracts (
  id uuid primary key default gen_random_uuid(),
  contract_number integer generated by default as identity unique,
  title text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz default now()
);

-- Every uploaded file belongs to a contract, tagged by its role in the bundle
create table documents (
  id uuid primary key default gen_random_uuid(),
  contract_id uuid references contracts(id) on delete cascade,
  role text not null check (role in ('original', 'annex', 'amendment', 'renewal', 'correspondence', 'other')),
  storage_path text not null,
  original_filename text not null,
  generated_filename text,
  extracted_text text,
  processing_status text not null default 'pending' check (processing_status in ('pending', 'processing', 'complete', 'failed')),
  uploaded_via text default 'ui',
  created_at timestamptz default now()
);

-- The "playbook" catalog: built-in fields and user-defined custom fields
create table metadata_fields (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  label text not null,
  category text not null,
  field_type text not null check (field_type in ('text', 'date', 'number', 'boolean', 'enum')),
  enum_options text[],
  playbook_prompt text not null,
  is_builtin boolean default false,
  created_at timestamptz default now()
);

-- The actual extracted (or manually entered) value, per contract, per field
create table metadata_values (
  id uuid primary key default gen_random_uuid(),
  contract_id uuid references contracts(id) on delete cascade,
  field_id uuid references metadata_fields(id) on delete cascade,
  value text,
  confidence numeric,
  confirmed boolean default false,
  source_document_id uuid references documents(id),
  evidence_page integer,
  evidence_text text,
  updated_at timestamptz default now(),
  unique (contract_id, field_id)
);

-- Typed links between contracts
create table contract_relationships (
  id uuid primary key default gen_random_uuid(),
  contract_a_id uuid references contracts(id) on delete cascade,
  contract_b_id uuid references contracts(id) on delete cascade,
  relationship_type text not null,
  confirmed boolean default false,
  created_at timestamptz default now()
);

-- Naming convention template (single row for pilot)
create table naming_settings (
  id uuid primary key default gen_random_uuid(),
  template text not null default '{contract_type}_{counterparty}_{effective_date}_{document_role}',
  keep_original_name boolean default true
);

-- Storage bucket (create in Supabase dashboard if this insert fails)
insert into storage.buckets (id, name, public)
values ('contracts', 'contracts', false)
on conflict (id) do nothing;

create policy "Authenticated users can read contract files"
on storage.objects for select to authenticated
using (bucket_id = 'contracts');

create policy "Service role manages contract files"
on storage.objects for all to service_role
using (bucket_id = 'contracts');

alter table contracts enable row level security;
alter table documents enable row level security;
alter table metadata_fields enable row level security;
alter table metadata_values enable row level security;
alter table contract_relationships enable row level security;
alter table naming_settings enable row level security;

create policy "Authenticated users can read contracts" on contracts for select to authenticated using (true);
create policy "Authenticated users can insert contracts" on contracts for insert to authenticated with check (true);
create policy "Authenticated users can update contracts" on contracts for update to authenticated using (true);

create policy "Authenticated users can read documents" on documents for select to authenticated using (true);
create policy "Authenticated users can insert documents" on documents for insert to authenticated with check (true);
create policy "Authenticated users can update documents" on documents for update to authenticated using (true);

create policy "Authenticated users can read metadata_fields" on metadata_fields for select to authenticated using (true);
create policy "Authenticated users can insert metadata_fields" on metadata_fields for insert to authenticated with check (true);

create policy "Authenticated users can read metadata_values" on metadata_values for select to authenticated using (true);
create policy "Authenticated users can insert metadata_values" on metadata_values for insert to authenticated with check (true);
create policy "Authenticated users can update metadata_values" on metadata_values for update to authenticated using (true);

create policy "Authenticated users can read relationships" on contract_relationships for select to authenticated using (true);
create policy "Authenticated users can insert relationships" on contract_relationships for insert to authenticated with check (true);

create policy "Authenticated users can read naming_settings" on naming_settings for select to authenticated using (true);
create policy "Authenticated users can update naming_settings" on naming_settings for update to authenticated using (true);
